[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8080

# Redirect da .com a .it
[[redirects]]
  from = "https://paroletaboo.com/*"
  to = "https://paroletaboo.it/:splat"
  status = 301
  force = true

# Redirect da .space a .it
[[redirects]]
  from = "https://paroletaboo.space/*"
  to = "https://paroletaboo.it/:splat"
  status = 301
  force = true

# Regola esistente per SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 