[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8080

# Language-specific redirects
[[redirects]]
  from = "/en/*"
  to = "/en/index.html"
  status = 200

[[redirects]]
  from = "/en"
  to = "/en/index.html"
  status = 200

# Redirect da .com a .it
[[redirects]]
  from = "https://paroletaboo.com/*"
  to = "https://paroletaboo.it/:splat"
  status = 301
  force = true

# Redirect da .space a .it
[[redirects]]
  from = "https://paroletaboo.space/*"
  to = "https://paroletaboo.it/:splat"
  status = 301
  force = true

# Prima tenta di servire i file statici generati
[[redirects]]
  from = "/rules"
  to = "/rules/index.html"
  status = 200

[[redirects]]
  from = "/en/rules"
  to = "/en/rules/index.html"
  status = 200

# Aggiungi altri percorsi statici qui se necessario

# Regola esistente per SPA (come fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200